services:
  db:
    image: postgres:13-alpine
    container_name: ebookreader_db
    environment:
      POSTGRES_DB: ebookreader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ebookreader"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ebookreader_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ebookreader
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    volumes:
      - ./backend/assets:/app/assets
    depends_on:
      db:
        condition: service_healthy

# Данные теперь сохраняются в локальные папки ./postgres_data и ./backend/assets
# Это гарантирует, что они не пропадут при перезагрузке Docker.
